import { lazy } from 'react'

/**
 * Lazy page component for every routed tool. Each tool is its own chunk, so
 * heavy dependencies (FFmpeg, codecs, ML models) load only when needed.
 */
export const TOOL_PAGES = {
  'ai-image': lazy(() => import('@/features/ai/image/AiImagePage')),
  'ai-video': lazy(() => import('@/features/ai/video/AiVideoPage')),

  'resume-builder': lazy(() => import('@/features/resume/ResumeBuilderPage')),
  'pdf-editor': lazy(() => import('@/features/pdf/editor/PdfEditorPage')),
  'images-to-pdf': lazy(() => import('@/features/pdf/ImagesToPdfPage')),
  'pdf-to-images': lazy(() => import('@/features/pdf/PdfToImagesPage')),
  'pdf-merge': lazy(() => import('@/features/pdf/MergePdfPage')),
  'pdf-split': lazy(() => import('@/features/pdf/SplitPdfPage')),
  'pdf-organize': lazy(() => import('@/features/pdf/OrganizePdfPage')),
  'pdf-compress': lazy(() => import('@/features/pdf/CompressPdfPage')),

  'image-compress': lazy(() => import('@/features/image/compress/CompressImagePage')),
  'image-convert': lazy(() => import('@/features/image/convert/ConvertImagePage')),
  'image-resize': lazy(() => import('@/features/image/resize/ResizeImagePage')),
  'image-crop': lazy(() => import('@/features/image/crop/CropImagePage')),
  'image-remove-bg': lazy(() => import('@/features/image/removeBackground/RemoveBackgroundPage')),
  'image-editor': lazy(() => import('@/features/image/editor/ImageEditorPage')),
  'image-watermark': lazy(() => import('@/features/image/watermark/WatermarkPage')),
  'image-metadata': lazy(() => import('@/features/image/metadata/MetadataPage')),
  'image-batch': lazy(() => import('@/features/image/batch/BatchImagePage')),
  'image-to-base64': lazy(() => import('@/features/image/base64/ImageToBase64Page')),
  'base64-to-image': lazy(() => import('@/features/image/base64/Base64ToImagePage')),
  'image-ico': lazy(() => import('@/features/image/ico/IcoConverterPage')),
  'svg-to-png': lazy(() => import('@/features/image/svg/SvgToPngPage')),
  'png-to-svg': lazy(() => import('@/features/image/svg/ImageToSvgPage')),
  'heic-to-jpg': lazy(() => import('@/features/image/heic/HeicToJpgPage')),
  'image-text': lazy(() => import('@/features/image/text/AddTextImagePage')),
  'image-censor': lazy(() => import('@/features/image/censor/CensorImagePage')),
  'image-collage': lazy(() => import('@/features/image/collage/CollagePage')),
  'image-border': lazy(() => import('@/features/image/border/BorderImagePage')),
  'image-filters': lazy(() => import('@/features/image/filters/FiltersImagePage')),
  'image-color-picker': lazy(() => import('@/features/image/colorPicker/ColorPickerPage')),
  'image-blur': lazy(() => import('@/features/image/effects/BlurImagePage')),
  'image-pixelate': lazy(() => import('@/features/image/effects/PixelateImagePage')),
  'image-grayscale': lazy(() => import('@/features/image/effects/GrayscaleImagePage')),
  'image-rotate': lazy(() => import('@/features/image/effects/RotateImagePage')),
  'image-flip': lazy(() => import('@/features/image/effects/FlipImagePage')),

  'video-compress': lazy(() => import('@/features/video/compress/CompressVideoPage')),
  'video-convert': lazy(() => import('@/features/video/convert/ConvertVideoPage')),
  'video-trim': lazy(() => import('@/features/video/trim/TrimVideoPage')),
  'video-crop': lazy(() => import('@/features/video/crop/CropVideoPage')),
  'video-resize': lazy(() => import('@/features/video/resize/ResizeVideoPage')),
  'video-mute': lazy(() => import('@/features/video/audio/MuteVideoPage')),
  'video-extract-audio': lazy(() => import('@/features/video/audio/ExtractAudioPage')),
  'video-speed': lazy(() => import('@/features/video/speed/VideoSpeedPage')),
  'video-rotate': lazy(() => import('@/features/video/rotate/RotateVideoPage')),
  'video-to-gif': lazy(() => import('@/features/video/gif/VideoToGifPage')),
  'gif-to-video': lazy(() => import('@/features/video/gif/GifToVideoPage')),
  'video-thumbnail': lazy(() => import('@/features/video/thumbnail/VideoThumbnailPage')),
  'video-loop': lazy(() => import('@/features/video/effects/LoopVideoPage')),
  'video-reverse': lazy(() => import('@/features/video/effects/ReverseVideoPage')),
  'video-fps': lazy(() => import('@/features/video/effects/VideoFpsPage')),
  'video-frames': lazy(() => import('@/features/video/frames/ExtractFramesPage')),
  'video-merge': lazy(() => import('@/features/video/merge/MergeVideosPage')),
  'video-text': lazy(() => import('@/features/video/overlay/VideoTextPage')),
  'video-watermark': lazy(() => import('@/features/video/overlay/VideoWatermarkPage')),
  'video-censor': lazy(() => import('@/features/video/censor/CensorVideoPage')),
  'video-filters': lazy(() => import('@/features/video/filters/VideoFiltersPage')),
  'video-fit': lazy(() => import('@/features/video/fit/FitVideoPage')),
  'video-split': lazy(() => import('@/features/video/split/SplitVideoPage')),
  'video-fade': lazy(() => import('@/features/video/fade/FadeVideoPage')),
  'video-add-audio': lazy(() => import('@/features/video/audio/AddAudioPage')),
}
